Fix: delivery view horizontal and vertical overflow
Azordev/maps-project pull request #112
Opened 2022-03-24 19:56 UTC by mdibuhossain

fixes #111 

#### Screenshots
![image](https://user-images.githubusercontent.com/59278819/159998711-ae363d3c-eb35-45b6-a91b-bc8d1c4e5162.png)

### Checklist:

- [x] Fix the words overlapping at page header.
- [x] Fix vertical overflow and make the view fill 100% of the viewport
- [x] Fix the horizontal overflow

2022-03-24 21:41 UTC, e-azocar requested changes
I did test it. The overlapping isn't there it's ok, but, the overflows are there yet
![image](https://user-images.githubusercontent.com/61360270/160013448-9f0084ab-19f4-4f5b-b75f-50fc4cdeea03.png)

2022-03-25 06:32 UTC, Israel-Laguan approved these changes

2022-03-25 13:45 UTC, Katsu08 approved these changes
It looks good on most screens! Good work!

2022-03-25 13:56 UTC, e-azocar approved these changes
Really good job

2022-03-25 13:57 UTC, merged