fix: confirm page title and subtitle size, image position and text color
Azordev/maps-project pull request #131
Opened 2022-04-11 16:31 UTC by Eghinner

### Description

Increased width image notebook, updated title and subtitle color, size, and weight.

fixes #126 

#### Screenshots

![image (1)](https://user-images.githubusercontent.com/71513679/162786471-35f3a32b-88e8-4ca2-be02-cf404fe872dc.png)

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### How to test it

Go to 'confirm/1'

### Checklist:

- [x] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [x] Doesn't have unnecessary comments or debugging code.
- [x] The branch is updated with the last dev branch changes.

2022-04-11 16:55 UTC, Israel-Laguan commented on src/components/Text.jsx
> +
extra line

2022-04-11 16:57 UTC, Israel-Laguan approved these changes

2022-04-13 13:07 UTC, e-azocar approved these changes

2022-04-13 14:28 UTC, Katsu08 approved these changes
Good work

2022-04-13 16:40 UTC, e-azocar requested changes
On some screen sizes this happens. For example:
width1345px 
height 600px
![image](https://user-images.githubusercontent.com/61360270/163229161-5caf3db0-ac6d-45ff-a2ef-b99c86734ff2.png)

I think is problem with height, because this doesn't happen on higher. For example:
width1345px 
height 800px
![image](https://user-images.githubusercontent.com/61360270/163228510-86ff76f5-3d71-41a4-b3d4-33a36fb30a21.png)

2022-04-14 14:24 UTC, Eghinner commented
> On some screen sizes this happens. For example: width1345px height 600px ![image](https://user-images.githubusercontent.com/61360270/163229161-5caf3db0-ac6d-45ff-a2ef-b99c86734ff2.png)
> 
> I think is problem with height, because this doesn't happen on higher. For example: width1345px height 800px ![image](https://user-images.githubusercontent.com/61360270/163228510-86ff76f5-3d71-41a4-b3d4-33a36fb30a21.png)
![heigth](https://user-images.githubusercontent.com/71513679/163410748-9e8c97c3-8de5-452f-953d-9264ac1e25d0.gif)

2022-04-15 21:34 UTC, e-azocar approved these changes

2022-04-18 13:55 UTC, merged