improve footer
Azordev/maps-project pull request #175
Opened 2022-06-20 10:03 UTC by mdrianislam0or1

### Description
 Improve footer styles in map view - Desktop view #171 

#### Screenshots
![fix#171](https://user-images.githubusercontent.com/67714964/174578322-42ad4c91-27bb-4386-a1a5-7d165cf95863.jpg)

2022-06-20 13:48 UTC, Israel-Laguan approved these changes

2022-06-20 13:56 UTC, e-azocar approved these changes

2022-06-20 14:27 UTC, victor-heliomar requested changes
Hmm please check code style, the rest looks good

2022-06-20 14:27 UTC, victor-heliomar commented on src/pages/Delivery/Delivery.layout.jsx
> +} from './Delivery.styled'
I prefer one line for each one

```suggestion
import {
  ChatBtn, 
  ChatBtnContainer, 
  FooterMap,
  FooterMapAddress, 
  HeaderMap,
  HeaderSubTitle, 
  HeaderText, 
  HeaderTitle, 
  MapContainer, 
  MapLayoutContainer
} from './Delivery.styled'
```

Please check if is possible to run Prettier

2022-06-21 12:36 UTC, angelik0828 commented
@mdrianislam0or1 

1. The text used in the localization is not bold and is not proportionally sized.
2. The text used in "estimated time of arrival" is not bold and should not be as large
3. The text "contact us" should be blank and in normal type.

![image](https://user-images.githubusercontent.com/4030477/174799757-ef12eaf6-51ab-4f7e-8728-04f40f2ed588.png)

2022-06-23 00:23 UTC, victor-heliomar commented on src/pages/Delivery/Delivery.layout.jsx
> +            <Text medium bold margin="8" style={{ textTransform: 'lowercase',fontSize:'23px', color:'#003B62',fontWeight:'700'}}>
please left enough space to do more readable your code
```suggestion
            <Text medium bold margin="8" style={{ textTransform: 'lowercase', fontSize: '23px',  color: '#003B62', fontWeight: '700' }}>
```

2022-06-28 02:23 UTC, Israel-Laguan approved these changes

2022-06-28 13:26 UTC, angelik0828 commented
@mdrianislam0or1 I want to ask if the change was made?

2022-06-29 21:11 UTC, angelik0828 approved these changes

2022-06-30 15:23 UTC, merged