feat: add basic config
Azordev/maps-project pull request #55
Opened 2022-02-17 04:54 UTC by denisosuna

### Description

Please include a summary of the change.

fixes #16 #29 #46 #47

#### Screenshots

If applicable, add screenshots about your changes

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ ] The branch is updated with the last dev branch changes.

2022-02-17 13:48 UTC, Israel-Laguan approved these changes

2022-02-17 15:02 UTC, Katsu08 requested changes
I don't see emotion js in package json, can you check if this was added? @denisosuna 

https://emotion.sh/docs/introduction

2022-02-17 15:02 UTC, heliomar-pena commented on package.json
> +    "styled-components": "^5.3.3",
We have decided to do not use styled components, instead we want to use emotion js

2022-02-17 15:36 UTC, e-azocar commented
@denisosuna about the `spelling`, I think we only should add it to verify the commits, but not verify all the files

2022-02-17 15:42 UTC, e-azocar requested changes
@denisosuna  about the spelling, I think we only should add it to verify the commits, but not verify all the files

2022-02-18 18:30 UTC, Katsu08 commented on src/App.js
> +          Learn React maro
Maro?

2022-02-18 18:50 UTC, Katsu08 commented
I check and look like the spelling is not working. They have accepted this commit msg: "fix: added kfdsfs things"

![imagen](https://user-images.githubusercontent.com/66505715/154743583-f7f116fa-65a6-4677-b5e9-f9c5524d99d6.png)

2022-02-18 19:25 UTC, e-azocar commented
> I check and look like the spelling is not working. They have accepted this commit msg: "fix: added kfdsfs things"
> 
> ![imagen](https://user-images.githubusercontent.com/66505715/154743583-f7f116fa-65a6-4677-b5e9-f9c5524d99d6.png)

So, the spelling is not working?

2022-02-23 15:25 UTC, Katsu08 approved these changes
I have tested and is working correctly! Good work!

2022-02-23 15:46 UTC, e-azocar approved these changes

2022-02-23 15:47 UTC, merged