feat: update-the-confirm-view
Azordev/maps-project pull request #70
Opened 2022-02-26 07:40 UTC by arodriguezl9302

### Description

Changed header styles text styles, put back button image, changed form styles, changed text color, border and background in fields add report button and change button color confirm all this in mobile view

fixes #50 

#### Screenshots

![image](https://user-images.githubusercontent.com/24697827/155834682-a257f14a-4e37-496a-a0ef-fdede9339e6d.png)

#### Type of change

Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

1. Go to '/confirm/{id}'

### Checklist:

- [ ] Change header color #56ACDE
- [ ] Change fonts type: popins bold and color #002740 size according to design
- [ ] Place button on the back top left according to the image in figma
- [ ] Change size and color of text field, background color #C4C4C4 23%, border #5F6769 to 1px, font used regular popins, all fields uppercase.
- [ ] Change button styles report color #F74326 and confirmation #005D9D buttons next to each other centered with respect to the form

2022-02-28 13:59 UTC, e-azocar requested changes
## Please check why is not centered.
And the view has a horizontal overflow
![image](https://user-images.githubusercontent.com/61360270/155996675-f2b0c453-c11b-4daa-a1ea-570c7d30c08d.png)
![image](https://user-images.githubusercontent.com/61360270/155996689-24d90567-3e41-4d9f-946a-00d24ea04418.png)

2022-02-28 14:10 UTC, e-azocar requested changes
## At some display sizes this happens:
For example 970px of width 
![image](https://user-images.githubusercontent.com/61360270/155997035-0912c7b3-c6e9-4047-8d9d-5e6dbbcb3be2.png)

2022-02-28 17:05 UTC, angelik0828 commented
the image of the notebook does not correspond to that of the design, it does not have the fonts or the color that is seen in the design, the style was not changed in the title, the text fields are not in the regular style either, also the color in the fields.
![image](https://user-images.githubusercontent.com/4030477/156025893-dbf9963d-924d-4073-b061-3d244d3fc1a5.png)
![image](https://user-images.githubusercontent.com/4030477/156025921-e286bed6-34f6-47e2-a47a-9e26d18acd76.png)
![image](https://user-images.githubusercontent.com/4030477/156025971-59afbd11-b24c-418e-bdfd-63700e504f09.png)
this is how it should look
![view_report](https://user-images.githubusercontent.com/4030477/156026023-759b9b07-0c6c-485a-9fd6-f2cef550bbd9.jpg)

2022-02-28 17:43 UTC, arodriguezl9302 commented
Hello, thank you very much for the criticism, in reality there is not much description in the issues, for example, the colors of each issue that I made were not the same, the font was not implemented as such, the colors did not exist

2022-02-28 19:09 UTC, Katsu08 requested changes
Good job with the task! I left you some comments about how to improve the code that I have notice

2022-02-28 19:09 UTC, heliomar-pena commented on src/components/Form/Form.jsx
> +import { ButtonContainer, FormButtonPrimary, FormButtonDanger, FormContainer } from './Form.styled'
Why not to use a FormButton that can change the color using a prop?

2022-02-28 19:09 UTC, heliomar-pena commented on src/components/Form/Form.jsx
> +const Form = ({ children, onSubmit, formData = e => e, FormButtonConfirm = 'Confirmar', FormButtonReport = 'Reportar' }) => {
I think this isn't a good way to handle the Report Button. Because the developer has no freedom to add another FormButton that Confirm or Report.

I think should change the name for: "FormButtonPrimary" and "FormButtonSecondary"

Other option is just left the "FormButtonTitle" param, and add a Slot (children) to the develop can add another think that he need like secondary button, and add the FormButtonReport as Children

2022-02-28 19:09 UTC, heliomar-pena commented on src/components/Form/Form.styled.jsx
> +    width: 350px;
Since FormButtonPrimary and FormButtonDanger have this same style, in Desktop this looks so bad. This can cause problems if the developer decide only put 1 button or put 2 buttons. Maybe think in another

2022-02-28 19:09 UTC, heliomar-pena commented on src/components/FormInput.jsx
> +  height: 53px;
Please add `max-width: 100%` to avoid overflow in mobile size

2022-02-28 19:09 UTC, Katsu08 commented on src/pages/Confirm/Confirm.layout.jsx
> +        <Text as="h1" color="third" weight700 xlg bold>
Really is working "weight700"? I think doesn't look good have attributes with numbers. Maybe looks better if you change the name for a reference, for example: weight 700 can be called "semibold", while weight 800 can be called "bold", and weight 400 can be called "normal", what do you think?

```suggestion
        <Text as="h1" color="third" weight700 xlg bold>
```

2022-02-28 19:09 UTC, heliomar-pena commented on src/pages/Confirm/index.jsx
> +              <FormInput placeholder="CELULAR" name="phone" value={value} onChange={handleFormChange} />
You can too modify the name case using CSS: https://developer.mozilla.org/es/docs/Web/CSS/text-transform.

I think is better practice because you not need write ALL IN UPPERCASE and do changes later is more easily

2022-02-28 19:09 UTC, heliomar-pena commented on src/styles/text.js
> +    font-weight: 700 !important;
I think the `important` can cause problems since is not predictable to the developer that is creating new CSS

2022-02-28 19:30 UTC, angelik0828 commented
> Hello, thank you very much for the criticism, in reality there is not much description in the issues, for example, the colors of each issue that I made were not the same, the font was not implemented as such, the colors did not exist

You are right many things were not implemented, the existing source is another in fact it is not critical it is a suggestion we are here to help us, if you have doubts you can mention and with pleasure.

2022-03-01 02:05 UTC, arodriguezl9302 commented on src/components/Form/Form.jsx
> +const Form = ({ children, onSubmit, formData = e => e, FormButtonConfirm = 'Confirmar', FormButtonReport = 'Reportar' }) => {
The problem is that they were using the same form for all the screens

2022-03-01 04:50 UTC, arodriguezl9302 commented
### INFORMATION

I have tried to repair everything by taking a figma image, I remain at your disposal

###THE TEXT IN THAT FONT DOES NOT TAKE THE SAME VISUAL EFFECT AS IT DOES IN FIGA, PLEASE REVIEW THAT THEME

![image](https://user-images.githubusercontent.com/24697827/156106643-25d6b549-eace-41ab-a1bb-0cc3c891aa63.png)

![image](https://user-images.githubusercontent.com/24697827/156106690-f532e80d-f0a6-4612-a1c2-415d22e5bc77.png)

in 970px
![image](https://user-images.githubusercontent.com/24697827/156106856-b707b087-0354-46f4-b4ca-a661365564aa.png)

2022-03-01 15:15 UTC, Katsu08 requested changes
Good work! Thanks for the changes! I have left you some little comments. Large comments can be moved to a new issue, but please check the comments about remove comments and other small comments

2022-03-01 15:15 UTC, heliomar-pena commented on src/components/Form/Form.jsx
> +      { FormButtonSecondaryTitle != null ? <FormButtonSecondary type="submit">{FormButtonSecondaryTitle}</FormButtonSecondary> : null}
As doesn't exists an "else" action, you can to use:

```suggestion
      { FormButtonSecondaryTitle && <FormButtonSecondary type="submit">{FormButtonSecondaryTitle}</FormButtonSecondary> }
```

2022-03-01 15:15 UTC, heliomar-pena commented on src/components/Form/Form.styled.jsx
> +  }
Please remove comment

2022-03-01 15:15 UTC, heliomar-pena commented on src/components/FormInput.jsx
> +  height: 53px;
What do you think about add `max-width`?

2022-03-01 15:15 UTC, heliomar-pena commented on src/components/FormInput.jsx
> +    //height: auto;
Please remove comments

2022-03-01 15:15 UTC, heliomar-pena commented on src/components/FormInput.jsx
> +    width: 90%;
What do you think about `width: 350px; max-width: 90%` or `width: 90%; max-width: 350px`? To left a top limit

2022-03-01 15:15 UTC, heliomar-pena commented on src/components/Text.jsx
> +    //${[text.white, text.xs]}
please remove comments

2022-03-01 15:15 UTC, heliomar-pena commented on src/layouts/Splitted.styled.jsx
>      justify-content: center;
I think is better to use `#FFFFFF` color instead of not use any color

2022-03-01 15:15 UTC, heliomar-pena commented on src/pages/Confirm/Confirm.styled.jsx
> +  }
I think is better to use position absolute or relative to position the image.

An idea that you can try is:

`
margin-left: auto;
position: relative;
left: 25px;
`

2022-03-01 15:15 UTC, heliomar-pena commented on src/styles/text.js
> +    font-weight: 700 !important;
What do you think about removing important? it is not constant with the other properties

2022-03-01 15:15 UTC, heliomar-pena commented on src/styles/text.js
> +   //line-height: 27px;
Remove comment please

2022-03-01 15:17 UTC, Katsu08 commented on src/components/Text.jsx
> +    //${[text.white, text.xs]}
If you remove this line please remove line 27 too, since "The most common" doesn't contains nothing

2022-03-01 15:19 UTC, Katsu08 commented on src/pages/Confirm/Confirm.styled.jsx
> +  }
Other idea is to use Flex or Grid in a container to positioning the image

2022-03-01 15:57 UTC, arodriguezl9302 commented
ok, today I accept the comments, we are learning @Katsu08

2022-03-01 17:37 UTC, arodriguezl9302 commented on src/components/Form/Form.jsx
> +      { FormButtonSecondaryTitle != null ? <FormButtonSecondary type="submit">{FormButtonSecondaryTitle}</FormButtonSecondary> : null}
ready

2022-03-01 17:37 UTC, arodriguezl9302 commented on src/components/Form/Form.styled.jsx
> +  }
ready

2022-03-01 17:38 UTC, arodriguezl9302 commented on src/components/FormInput.jsx
> +    //height: auto;
ready

2022-03-01 17:44 UTC, arodriguezl9302 commented on src/components/FormInput.jsx
> +    width: 90%;
ready

2022-03-01 17:45 UTC, arodriguezl9302 commented on src/components/Text.jsx
> +    //${[text.white, text.xs]}
ready

2022-03-01 17:47 UTC, arodriguezl9302 commented on src/layouts/Splitted.styled.jsx
>      justify-content: center;
ready

2022-03-01 17:55 UTC, arodriguezl9302 commented on src/pages/Confirm/Confirm.styled.jsx
> +  }
ready

2022-03-01 17:56 UTC, arodriguezl9302 commented on src/styles/text.js
> +   //line-height: 27px;
ready

2022-03-01 18:01 UTC, arodriguezl9302 commented
@Katsu08 I just made a commit

2022-03-01 18:50 UTC, Katsu08 approved these changes
Perfect! so thanks. I left you only one optional comment, in 1 hour I will merge the branch

2022-03-01 18:50 UTC, Katsu08 commented on src/components/FormInput.jsx
> +  max-width: 100%;
You can left width 268px, max-width is only to avoid that small screen has overflow content
```suggestion
  width: 268px;
  max-width: 100%;
```

2022-03-01 18:50 UTC, Katsu08 commented on src/pages/Confirm/Confirm.styled.jsx
> +    top: 232px;
I would suggest not to use big static values to position HTML elements, this is not predictable for other developers that want to collaborate with you. And this way of doing things is not adaptable for other screen sizes than yours. But how desktop is not the objective of this pull request I think this is not needed to resolve for now. Maybe in another PR.

2022-03-01 21:25 UTC, merged