feat: #54 colors and images changed
Azordev/maps-project pull request #90
Opened 2022-03-10 19:30 UTC by ygamboalh

### Description
Images and colors were changed. 

fixes #54  (issue)
#### Screenshots
![image](https://user-images.githubusercontent.com/92061563/157739410-2ee62350-d5aa-406d-ad2a-e64c7f4874f1.png)
![image](https://user-images.githubusercontent.com/92061563/157739568-9fd9f717-8099-494c-b17f-8b938cf3f315.png)
![image](https://user-images.githubusercontent.com/92061563/157739892-b0ede854-4cae-43d2-9ac6-f956036bdff9.png)

2022-03-10 21:10 UTC, Katsu08 requested changes
- [ ] In desktop should be divided into two vertical sections too
- [ ] Color should be blue instead of black

![imagen](https://user-images.githubusercontent.com/66505715/157754563-7c9d99e9-d588-49d0-8586-deb719674787.png)

![imagen](https://user-images.githubusercontent.com/66505715/157754684-2a318a70-3575-448e-b390-bf82b60401f0.png)

- [ ] In mobile the image looks so big (538px)

![imagen](https://user-images.githubusercontent.com/66505715/157754789-6a240fa2-76cf-493b-a9e5-4d55000f0148.png)

- [ ] In mobile and desktop should exist a better way to positioned images to do the homepage looks like the original design

2022-03-10 21:11 UTC, Katsu08 commented
I will up the E.E to 2 since I notice the issue can be a little more difficult than just change images

2022-03-10 21:47 UTC, Israel-Laguan approved these changes

2022-03-15 15:45 UTC, angelik0828 commented
I think the text hello! It's not the right thickness, it's too thin, and the title should have a smaller gap with the subtitle.

![image](https://user-images.githubusercontent.com/4030477/158413606-300f94cf-b35c-4416-9075-5e998f7db711.png)

the button is very thick it looks very big

2022-03-16 01:36 UTC, closed without merging